// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.3
// source: protos/hackathon.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Hackathon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                int64  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Location          string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	StartDate         string `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	TeamSize          int32  `protobuf:"varint,6,opt,name=team_size,json=teamSize,proto3" json:"team_size,omitempty"`
	NumberOfTeams     int32  `protobuf:"varint,7,opt,name=number_of_teams,json=numberOfTeams,proto3" json:"number_of_teams,omitempty"`
	SubscriptionsOpen bool   `protobuf:"varint,8,opt,name=subscriptions_open,json=subscriptionsOpen,proto3" json:"subscriptions_open,omitempty"`
}

func (x *Hackathon) Reset() {
	*x = Hackathon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_hackathon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hackathon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hackathon) ProtoMessage() {}

func (x *Hackathon) ProtoReflect() protoreflect.Message {
	mi := &file_protos_hackathon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hackathon.ProtoReflect.Descriptor instead.
func (*Hackathon) Descriptor() ([]byte, []int) {
	return file_protos_hackathon_proto_rawDescGZIP(), []int{0}
}

func (x *Hackathon) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Hackathon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hackathon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hackathon) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Hackathon) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Hackathon) GetTeamSize() int32 {
	if x != nil {
		return x.TeamSize
	}
	return 0
}

func (x *Hackathon) GetNumberOfTeams() int32 {
	if x != nil {
		return x.NumberOfTeams
	}
	return 0
}

func (x *Hackathon) GetSubscriptionsOpen() bool {
	if x != nil {
		return x.SubscriptionsOpen
	}
	return false
}

var File_protos_hackathon_proto protoreflect.FileDescriptor

var file_protos_hackathon_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x02, 0x0a, 0x09, 0x48, 0x61, 0x63,
	0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f,
	0x66, 0x5f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x66, 0x54, 0x65, 0x61, 0x6d, 0x73, 0x12, 0x2d, 0x0a, 0x12,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x6f, 0x70,
	0x65, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x2c, 0x5a, 0x2a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x61, 0x67, 0x6f,
	0x74, 0x62, 0x6c, 0x2f, 0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x73, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_hackathon_proto_rawDescOnce sync.Once
	file_protos_hackathon_proto_rawDescData = file_protos_hackathon_proto_rawDesc
)

func file_protos_hackathon_proto_rawDescGZIP() []byte {
	file_protos_hackathon_proto_rawDescOnce.Do(func() {
		file_protos_hackathon_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_hackathon_proto_rawDescData)
	})
	return file_protos_hackathon_proto_rawDescData
}

var file_protos_hackathon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_hackathon_proto_goTypes = []interface{}{
	(*Hackathon)(nil), // 0: Hackathon
}
var file_protos_hackathon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_hackathon_proto_init() }
func file_protos_hackathon_proto_init() {
	if File_protos_hackathon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_hackathon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hackathon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_hackathon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_hackathon_proto_goTypes,
		DependencyIndexes: file_protos_hackathon_proto_depIdxs,
		MessageInfos:      file_protos_hackathon_proto_msgTypes,
	}.Build()
	File_protos_hackathon_proto = out.File
	file_protos_hackathon_proto_rawDesc = nil
	file_protos_hackathon_proto_goTypes = nil
	file_protos_hackathon_proto_depIdxs = nil
}
