// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.3
// source: protos/team.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type T_SHIRT_SIZE int32

const (
	T_SHIRT_SIZE_S  T_SHIRT_SIZE = 0
	T_SHIRT_SIZE_M  T_SHIRT_SIZE = 1
	T_SHIRT_SIZE_L  T_SHIRT_SIZE = 2
	T_SHIRT_SIZE_XL T_SHIRT_SIZE = 3
)

// Enum value maps for T_SHIRT_SIZE.
var (
	T_SHIRT_SIZE_name = map[int32]string{
		0: "S",
		1: "M",
		2: "L",
		3: "XL",
	}
	T_SHIRT_SIZE_value = map[string]int32{
		"S":  0,
		"M":  1,
		"L":  2,
		"XL": 3,
	}
)

func (x T_SHIRT_SIZE) Enum() *T_SHIRT_SIZE {
	p := new(T_SHIRT_SIZE)
	*p = x
	return p
}

func (x T_SHIRT_SIZE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (T_SHIRT_SIZE) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_team_proto_enumTypes[0].Descriptor()
}

func (T_SHIRT_SIZE) Type() protoreflect.EnumType {
	return &file_protos_team_proto_enumTypes[0]
}

func (x T_SHIRT_SIZE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use T_SHIRT_SIZE.Descriptor instead.
func (T_SHIRT_SIZE) EnumDescriptor() ([]byte, []int) {
	return file_protos_team_proto_rawDescGZIP(), []int{0}
}

type Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID           int64          `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name         string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Confirmed    bool           `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	HackathonId  int64          `protobuf:"varint,4,opt,name=hackathon_id,json=hackathonId,proto3" json:"hackathon_id,omitempty"`
	Participants []*Participant `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
}

func (x *Team) Reset() {
	*x = Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_team_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_protos_team_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_protos_team_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Team) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Team) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *Team) GetHackathonId() int64 {
	if x != nil {
		return x.HackathonId
	}
	return 0
}

func (x *Team) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

type Participant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int64        `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name       string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email      string       `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhotoUrl   string       `protobuf:"bytes,4,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Phone      string       `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	TShirtSize T_SHIRT_SIZE `protobuf:"varint,6,opt,name=t_shirt_size,json=tShirtSize,proto3,enum=T_SHIRT_SIZE" json:"t_shirt_size,omitempty"`
	TeamId     int64        `protobuf:"varint,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *Participant) Reset() {
	*x = Participant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_team_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_protos_team_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_protos_team_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Participant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Participant) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Participant) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Participant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Participant) GetTShirtSize() T_SHIRT_SIZE {
	if x != nil {
		return x.TShirtSize
	}
	return T_SHIRT_SIZE_S
}

func (x *Participant) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

var File_protos_team_proto protoreflect.FileDescriptor

var file_protos_team_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x9d, 0x01, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x21,
	0x0a, 0x0c, 0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x49,
	0x64, 0x12, 0x30, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x73, 0x22, 0xc4, 0x01, 0x0a, 0x0b, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x2f, 0x0a, 0x0c, 0x74, 0x5f, 0x73, 0x68, 0x69, 0x72, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x54, 0x5f, 0x53, 0x48, 0x49, 0x52, 0x54,
	0x5f, 0x53, 0x49, 0x5a, 0x45, 0x52, 0x0a, 0x74, 0x53, 0x68, 0x69, 0x72, 0x74, 0x53, 0x69, 0x7a,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x2a, 0x2b, 0x0a, 0x0c, 0x54, 0x5f,
	0x53, 0x48, 0x49, 0x52, 0x54, 0x5f, 0x53, 0x49, 0x5a, 0x45, 0x12, 0x05, 0x0a, 0x01, 0x53, 0x10,
	0x00, 0x12, 0x05, 0x0a, 0x01, 0x4d, 0x10, 0x01, 0x12, 0x05, 0x0a, 0x01, 0x4c, 0x10, 0x02, 0x12,
	0x06, 0x0a, 0x02, 0x58, 0x4c, 0x10, 0x03, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x61, 0x67, 0x6f, 0x74, 0x62, 0x6c, 0x2f,
	0x68, 0x61, 0x63, 0x6b, 0x61, 0x74, 0x68, 0x6f, 0x6e, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_team_proto_rawDescOnce sync.Once
	file_protos_team_proto_rawDescData = file_protos_team_proto_rawDesc
)

func file_protos_team_proto_rawDescGZIP() []byte {
	file_protos_team_proto_rawDescOnce.Do(func() {
		file_protos_team_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_team_proto_rawDescData)
	})
	return file_protos_team_proto_rawDescData
}

var file_protos_team_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_team_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_team_proto_goTypes = []interface{}{
	(T_SHIRT_SIZE)(0),   // 0: T_SHIRT_SIZE
	(*Team)(nil),        // 1: Team
	(*Participant)(nil), // 2: Participant
}
var file_protos_team_proto_depIdxs = []int32{
	2, // 0: Team.participants:type_name -> Participant
	0, // 1: Participant.t_shirt_size:type_name -> T_SHIRT_SIZE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_team_proto_init() }
func file_protos_team_proto_init() {
	if File_protos_team_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_team_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_team_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Participant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_team_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_team_proto_goTypes,
		DependencyIndexes: file_protos_team_proto_depIdxs,
		EnumInfos:         file_protos_team_proto_enumTypes,
		MessageInfos:      file_protos_team_proto_msgTypes,
	}.Build()
	File_protos_team_proto = out.File
	file_protos_team_proto_rawDesc = nil
	file_protos_team_proto_goTypes = nil
	file_protos_team_proto_depIdxs = nil
}
